# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0831e394c566388cb62c332cef2cd58b51adc434040c82ffdeb6ecc0450da8f194b40cff2fc69fe1986872225b4f20dddd142706b1c61d3213edbe13800ed2c4

test:
  secret_key_base: 05049675edc29b5ba5b9a409f6f1d16dd34e4a97b3421502cd6a1200c782435668055aa355d20d9180f4fce731b1e45ffde6da00fd87441387b30a0482d6a63b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
